### ISSUE TITLE
Docsets gone

### ISSUE THREAD

**Issue by c-had** [orbotix/Sphero-iOS-SDK#37]
Hello,

I'm just starting to get my feet wet with Sphere development. I pulled today and was surprised to see all the docsets had been removed from the repo. Was this done intentionally? They are quite handy (I view them through Dash) and don't seem to be replaced by the new documentation site (though it is a very helpful site).

**Comment by VVes** [comment]
We intentionally removed the docsets for now as the SDK interface has gone through a major overhaul and the previous docset is now out-of-date.  We chose to go the route of a curated, community editable wiki style site in order to provide the most accurate and up to date documentation.  You can fork the docs site for a local copy if necessary.
