### ISSUE TITLE
RKMagnetometerData

### ISSUE THREAD

**Issue by citysite102** [orbotix/Sphero-iOS-SDK#47]
Hello, I try to get the Magnetometer sensor data from the device with following data streaming mask:
 `RKDataStreamingMask mask =  RKDataStreamingMaskAccelerometerFilteredAll |
        RKDataStreamingMaskGyroXFiltered |
        RKDataStreamingMaskGyroYFiltered |
        RKDataStreamingMaskGyroZFiltered |
        RKDataStreamingMaskMagnetometerZFiltered |
        RKDataStreamingMaskIMUAnglesFilteredAll;`
But I'll get an error as following.
![2016-03-12 4 24 19](https://cloud.githubusercontent.com/assets/6985923/13721918/de4e8b9e-e86f-11e5-89e2-e2f7081f433d.png)
with the error message like
 `*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[_NSInlineData getBytes:range:]: range {20, 1} exceeds data length 20'`
However, if I remove RKDataStreamingMaskMagnetometerZFiltered from the mask, everything just works perfect : ], is there any information or restriction about the Magnetometer sensor data?

**Comment by zenelk** [comment]
I'll get this on the queue to be looked at. I can't think of anything for you to try in the meantime, however.

**Comment by zenelk** [comment]
Hey there, so in reviewing the stack, the reason this is occurring is that magnetometer hasn't actually been present in robots since the older versions of Sphero. This crash is happening because you're requesting data that doesn't exist in the packet. I can get this on the board to have a bounds check, but my guess is that it will be a really low priority. For now you should just not request the data.
